### ISSUE TITLE
Maritza_Garcia_Sanchez

### ISSUE THREAD

**Issue by Maritza2893** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Maritza2893#1]
[Maritza_Garcia_Sanchez.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Maritza2893/files/12567218/Maritza_Garcia_Sanchez.pdf)

**Comment by DiegoLV117** [comment]
Portada 25%
Procedimiento 22%
Figuras,ilustraciones y fotografias 25%
Resultados y Clnclusiones 22%                     
  Calificacion 19/20                 
 Calificado por el equipo de Elisa Sanchez Coronel

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
